version: '3.1'

services:

  mongo:
    container_name: "mongo-local"
    image: mongo
    command: mongod
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
     - "27017:27017"